Repository SMU-Capstone/client, pull requests merged in 2022-05, with the labels that each got.

#10 쓰레기통 관리기능(추가/철거/청소신청) UI 구현
  .gitignore
  lib/pages/main-drawer.dart
  lib/widgets/trash-manage.dart
Labels: enhancement, FRONT

#12 쓰레기통 관리위젯 ui 수정
  lib/widgets/trash-manage.dart
Labels: FRONT, FIX

#13 Feat : 쓰레기통좌표를 통한 마커 가져오기
  lib/pages/main-map.dart
  lib/utils/main-service.dart
Labels: FRONT

#14 refactor: main-map.dart의 futurebuilder삭제 후, 리팩토링
  lib/pages/main-map.dart
Labels: FRONT, Refactoring

#15 STYLE: Loading화면 생성
  assets/images/.gitkeep
  assets/images/loading.jpeg
  lib/pages/loading.dart
  lib/pages/main-map.dart
  pubspec.yaml
Labels: FRONT

#16 FIX: Marker의 크기 조정
  lib/pages/main-map.dart
Labels: FRONT, FIX

#18 FIX: 종류별로 쓰레기통 좌표를 가져오도록 수정
  lib/pages/main-map.dart
  lib/utils/main-service.dart
Labels: FRONT, API, FIX

#19 FEAT: 마커 클릭시, 쓰레기통 정보창 생성
  lib/pages/main-map.dart
Labels: FRONT

#20 FIX: 플라스크 서버와의 연동
  lib/utils/main-service.dart
  lib/widgets/camera.dart
Labels: FRONT, API, FIX

#21 쓰레기통 추가신청 및 청소신청 http 통신 구현
  lib/pages/main-map.dart
  lib/utils/main-service.dart
  lib/widgets/trash-manage.dart
Labels: FRONT, FIX

#22 FIX: 쓰레기통 추가 위젯 코드의 null aware 연산자 삭제
  lib/widgets/trash-manage.dart
Labels: FRONT, FIX

#23 FIX: 쓰레기통 추가 신청시 확인창 생성
  lib/widgets/trash-manage.dart
Labels: FRONT, FIX

#24 CHORE: 앱 이름 변경
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
Labels: FRONT, FIX
