Repository SMU-Capstone/client, pull requests merged in 2022-07, with the labels that each got.

#27 fix: main-map.dart 위젯 분리 및 GetX 일부 적용
  lib/controllers/dropdown-controller.dart
  lib/pages/main-page.dart
  lib/widgets/main-map.dart
Labels: FRONT, FIX, Refactoring

#29 fix : main.dart 파일 패키지 수정
  lib/main.dart
Labels: HOTFIX

#30 REFACTOR: camera.dart에 GetX를 이용한 상태관리 적용
  lib/controllers/camera-controller.dart
  lib/widgets/camera.dart
Labels: FRONT, Refactoring
