Repository SMU-Capstone/client, pull requests merged in 2022-08, with the labels that each got.

#31 SETTING: 번들 id 수정
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Runner.xcodeproj/project.pbxproj
Labels: FIX, Setting

#32 FEAT: 쓰레기 촬영 후 유형에 맞는 가장 가까운 쓰레기통 보여주는 기능
  lib/controllers/main-map-controller.dart
  lib/utils/main-service.dart
  lib/widgets/camera.dart
  lib/widgets/main-map.dart
Labels: enhancement, FRONT

#33 FIX: 안드로이드 패키지 명 변경에 따른 파일 수정
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/smu_capstone_bigdata/client/MainActivity.kt
  android/app/src/profile/AndroidManifest.xml
Labels: FIX

#34 FIX: 카메라로 쓰레기통 찾을 시, 원래 존재하던 마커 삭제
  lib/controllers/main-map-controller.dart
  lib/widgets/camera.dart
  lib/widgets/main-map.dart
Labels: FRONT, FIX

#36 FIX: 불필요한 의존성 주입 삭제
  lib/controllers/main-map-controller.dart
  lib/widgets/camera.dart
  lib/widgets/main-map.dart
Labels: FRONT, FIX

#37 FIX: 쓰레기통 찾기 시 정보를 표시함과 동시에 지도 이동 기능 추가
  lib/controllers/main-map-controller.dart
  lib/widgets/main-map.dart
Labels: enhancement, FRONT, FIX

#38 FIX/쓰레기통 꽉찬 여부 표시 api 연동 완료
  lib/controllers/main-map-controller.dart
  lib/widgets/main-map.dart
Labels: FRONT, FIX
